learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include(('learning_logs.urls',"learning_logs"),namespace='learning_logs')),
]

learning_logs/urls.py
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),

    url(r'^topics/$', views.topics, name='topics'),

    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
  
]

users/urls.py
from django.conf.urls import url 
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
   url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),

]

learning_logs/models.py
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from django.db import models

class Topic(models.Model):
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.text

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	class Meta:
		verbose_name_plural = 'entries'
	def __str__(self):
		return self.text[:50] + "..."

 
		

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}
		

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic, Entry
from django.http import HttpResponseRedirect
from django.urls import reverse 
from .forms import TopicForm,EntryForm

# Create your views here.
def index(request):
	return render(request, 'learning_logs/index.html')


def topics(request):
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
	topics = Topic.objects.order_by('date_added')
	if request.method != 'POST':
		form = TopicForm()
	else:
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request,topic_id):
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data = request.POST)
		if form.is_valid():
			new_entry = form.save(commit= False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))


def edit_entry(request,entry_id):
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic

	if request.method != 'POST':
		form = EntryForm(instance=entry)
	else:
		form = EntryForm(instance=entry,data = request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

	context = {'entry':entry,'topic':topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

learning_logs/templates/learning_logs/base.html
<p>
   <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
   <a href="{% url 'learning_logs:topics' %}">Topics</a> -
   {% if user.is_authenticated %}
       Hello, {{ user.username}}.
    {% else %}
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}

</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}


   <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>>
   <p>Edit entry:</p>

   <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
   	{% csrf_token %}
   	{{form.as_p}}
   	<button name='submit'>save changes</button>
   </form>



{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Learning Log helps you keep track of your learning, for any topic you're leanrning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}


   <p><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>>
   <p>Add a new entry:</p>

   <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
   	{% csrf_token %}
   	{{form.as_p}}
   	<button name='submit'>add entry</button>
   </form>



{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
   <p>Add a new topic:</p>

   <form action="{% url 'learning_logs:new_topic' %}" method='post'>
   	{% csrf_token %}
   	{{form.as_p}}
   	<button name='submit'>add topic</button>
   </form>



{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}


<p>Topic: {{topic}}</p>
<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
</p>

<ul>
{% for entry in entries %}
  <li>
  	<p>{{entry.date_added|date:'M d, Y H:i'}}</p>
  	<p>{{entry.text|linebreaks}}</p>
  	<p>
  		<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
  	</p>

  </li>
 {% empty %}
  <li>
  	There are no entries for this topic yet.
  </li>
 {% endfor %}
</ul>


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Topics</p>
    <ul>
        {% for topic in topics %}
          <li>
          	<a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
          </li>
        {% empty %}
           <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% block content %}

   {% if form.errors %}
   <p>Your username and password didn't match, Please try again.</p>>
   {% endif %}

   <form method="post" action="{% url 'users:login' %}" >
   	{% csrf_token %}
   	{{form.as_p}}
   	<button name='submit'>log in</button>
   	<input type="hidden" name="next" value="{% url 'learning_logs:index'%}" />
   </form>



{% endblock content %}